name: gnome-software
version: git
summary: Application manager for GNOME
description: |
  Software allows you to find and install new applications and system
  extensions and remove existing installed applications.

  GNOME Software showcases featured and popular applications with useful
  descriptions and multiple screenshots per application.
  Applications can be found either through browsing the list of categories
  or by searching.
  It also allows you to update your system using an offline update.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  gnome-software:
    command: bin/classic-launch classic ${SNAP}/usr/bin/gnome-software
    desktop: usr/share/applications/org.gnome.Software.desktop

parts:
  gnome-3-26:
    plugin: nil
    prepare: |
      apt-get -y update
      apt-get install -y software-properties-common
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt-get -y update
      apt-get -y dist-upgrade
  desktop-gtk3:
    after: [gnome-3-26]
  iso-codes:
    after: [desktop-gtk3]
    source: https://ftp.osuosl.org/pub/blfs/conglomeration/iso-codes/iso-codes-3.77.tar.xz
    plugin: autotools
    configflags: [--prefix=/snap/gnome-software/current/usr]
    organize:
      snap/gnome-software/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - gettext
      - python3
  gnome-desktop:
    after: [iso-codes]
    source: https://git.gnome.org/browse/gnome-desktop
    source-type: git
    source-tag: 3.26.2
    plugin: autotools
    prepare:
      sed -i.bak -e 's|.*ISO_CODES_PREFIX=.*|ISO_CODES_PREFIX=/snap/gnome-software/current/usr|g' configure.ac
    configflags:
      - --prefix=/usr
      - --disable-date-in-gnome-version
      - --with-gnome-distributor=Ubuntu
      - --disable-debug-tools
      - --disable-desktop-docs
      - --enable-introspection=no
    organize:
      snap/gnome-software/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - libglib2.0-dev
      - gnome-common
      - intltool
      - gnome-pkg-tools
      - gtk-doc-tools
      - docbook-xml
      - libx11-dev
      - xkb-data
      - libgdk-pixbuf2.0-dev
      - libgl1-mesa-dev
      - libgtk-3-dev
      - libxml2-dev
      - libglib2.0-doc
      - libgtk-3-doc
      - libseccomp-dev
      - libudev-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - gsettings-desktop-schemas-dev
      - yelp-tools
  snapd-glib:
    after: [gnome-3-26]
    source: https://github.com/snapcore/snapd-glib
    source-type: git
    plugin: autotools
    configflags: [--prefix=/usr, --disable-glibtest]
    organize:
      snap/gnome-software/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - intltool
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libjson-glib-dev
      - libpolkit-gobject-1-dev
      - libsoup2.4-dev
      - valac
  gnome-software:
    build-attributes: [no-system-libraries]
    after: [snapd-glib, gnome-desktop]
    source: .
    source-type: git
    prepare:
      sed -i.bak -e 's|Icon=org.gnome.Software$|Icon=${SNAP}/meta/gui/org.gnome.Software.png|g' src/org.gnome.Software.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/icons/hicolor/256x256/org.gnome.Software.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp snapbuild/src/org.gnome.Software.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
      - --prefix=/snap/gnome-software/current/usr
      - -Denable-gnome-desktop=true
      - -Denable-odrs=true
      - -Denable-ostree=false
      - -Denable-packagekit=true
      - -Denable-rpm=false
      - -Denable-snap=true
      - -Denable-fwupd=false
      - -Denable-flatpak=false
      - -Denable-limba=false
      - -Denable-ubuntu-reviews=true
      - -Denable-tests=false
      - -Denable-gspell=false
    organize:
      snap/gnome-software/current/usr: usr
    build-packages:
      - appstream
      - appstream-util
      - docbook-xsl
      - gsettings-desktop-schemas-dev
      - gtk-doc-tools
      - intltool
      - libappstream-glib-dev
      #- libfwupd-dev
      - libglib2.0-bin
      - libglib2.0-dev
      - libgtk-3-dev
      #- libgspell-1-dev
      - libgudev-1.0-dev
      - libjson-glib-dev
      - liboauth-dev
      - libpackagekit-glib2-dev
      - libpolkit-gobject-1-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libxml2-utils
      - meson
      - pkg-config
      - valgrind
      - xsltproc
    stage-packages:
      - libappstream-glib8
      - libsecret-1-0
      - appstream
      - packagekit
      #- libgspell-1-1
      #- libfwupd2
      - libgudev-1.0-0
      - liboauth0
      - hicolor-icon-theme
      - humanity-icon-theme
      - light-themes
      - ubuntu-mono
      - ubuntu-settings
  magic:
    after: [gnome-software]
    plugin: nil
    stage-packages:
      - libglib2.0-0
      - libglib2.0-bin
      - shared-mime-info
    install: |
      set -eux
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
  classic-launch:
    plugin: dump
    source: ./snap
    organize:
      classic-launch: bin/classic-launch
